version: "3.9"

services:
  app:
    build: .
    working_dir: /cli
    volumes:
      - ./:/cli
    depends_on:
      db:
        condition: service_completed_successfully
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bookstack
      MYSQL_USER: bookstack
      MYSQL_PASSWORD: bookstack
    volumes:
      - ./docker-mysql-init.sql:/docker-entrypoint-initdb.d/init.sql